### ISSUE TITLE
uWebSockets-express should stop utf-8 decoding the body

### ISSUE THREAD

**Issue by Brahmah** [colyseus/uWebSockets-express#33]
https://github.com/expressjs/body-parser/issues/494#issuecomment-1837465665

**Comment by Brahmah** [comment]
@endel Happy to when I get a chance, but just got to do a little more testing to ensure it doesn't break anything else...

**Comment by hunkydoryrepair** [comment]
What is status of this?
We just encounted failure on all of our endpoints when multibyte-characters are sent.
Is there an older version uWebSockets that works?

We get errors in raw-body of express `Request size did not match length` or something to that effect, because the `_rawbody` is made into a `string` so the `.length` is not the actually length in bytes, but length in characters.

if there is not a fix, I think we need to roll back to a working version.

**Comment by hunkydoryrepair** [comment]
https://github.com/colyseus/uWebSockets-express/pull/34

**Comment by endel** [comment]
Thanks for the PR @hunkydoryrepair. 🙏 

Hi @Brahmah, could you confirm if new version [1.3.6](https://github.com/colyseus/uWebSockets-express/releases/tag/1.3.6) fixes the issue you were having too, or if you were experiencing something else?

Cheers

**Comment by Brahmah** [comment]
Hi @endel 

I've just checked out the PR and it's identical to what I ended up doing internally so should fix the multi byte character issue we discussed in the comments.

Thanks for taking the initiative @hunkydoryrepair and apologies for leaving this stale.
